spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/freshmeet_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false # Опционально: показывать SQL запросы в логах